In [8]:
import cPickle, pickle
f = open('/home/shai/ExperimentsManager/metadata', 'r')
#obj1 = cPickle.load(f)
obj2 = pickle.load(f)

print obj1

KeyError: '\n'

In [28]:
import numpy as np
print np.geomspace(0.001, 2, 4, True)
print np.linspace(0.0001, 1.0, 24)

[  1.00000000e-03   1.25992105e-02   1.58740105e-01   2.00000000e+00]
[  1.00000000e-04   4.35739130e-02   8.70478261e-02   1.30521739e-01
   1.73995652e-01   2.17469565e-01   2.60943478e-01   3.04417391e-01
   3.47891304e-01   3.91365217e-01   4.34839130e-01   4.78313043e-01
   5.21786957e-01   5.65260870e-01   6.08734783e-01   6.52208696e-01
   6.95682609e-01   7.39156522e-01   7.82630435e-01   8.26104348e-01
   8.69578261e-01   9.13052174e-01   9.56526087e-01   1.00000000e+00]


In [1]:
import matplotlib
matplotlib.use('Qt4Agg')
import matplotlib.pyplot as plt
import numpy as np

from os import listdir
from os.path import isfile, join
import os
import re

import experiment
import matplotlib.pyplot as plt

from batch_provider import SimpleBatchProvider

import tensorflow as tf
import matplotlib.image as mpimg
import numpy as np


sess = tf.InteractiveSession()

/home/shai/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py:1350: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)


In [5]:
#input_dim, output_dim, dataset_size, batch_sizes
with tf.variable_scope('batch_providers') as scope:
    batch_prov = SimpleBatchProvider(input_dim=6, output_dim=1, dataset_size=5000, batch_size=5000)


sess.run(tf.local_variables_initializer())
sess.run(tf.global_variables_initializer())
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)
batch_prov.custom_runner.start_threads(sess)

batch_prov.set_data_source(sess=sess, data_name='train')

[<Thread(Thread-6, started daemon 140268590196480)>,
 <Thread(Thread-7, started daemon 140268581803776)>]

In [1]:
import matplotlib
matplotlib.use('qt5agg')
matplotlib.matplotlib_fname()

u'/home/shai/anaconda/lib/python2.7/site-packages/matplotlib/mpl-data/matplotlibrc'

In [5]:
import matplotlib
matplotlib.use('qt5agg')

In [6]:
#How does the generated input data scattered? 
xy = sess.run(batch_prov.batch())

In [23]:
xy[1][i]

array([-0.27243438], dtype=float32)

In [26]:
print xy
#for j in range(6):
#plt.plot(range(500), [xy[0][i][j] for i in range(500)])

#plt.plot([xy[0][i][0] for i in range(500)], [xy[0][i][1] for i in range(500)], 'o')
plt.plot([xy[0][i][0] for i in range(500)], [xy[1][i][0] for i in range(500)], 'o')

plt.show()

(array([[ 0.98714125,  1.92482996, -0.39929965, -0.10294835, -0.36234316,
        -0.18078448],
       [-0.30432692,  0.52725232,  0.17356163,  1.18113494,  0.38767877,
         0.13760562],
       [-0.23239829,  1.44989836, -0.0799812 ,  0.25192904,  0.15566488,
        -1.37094629],
       ..., 
       [ 0.29380456, -1.28522992,  0.07191695, -1.05055964,  0.78657556,
        -0.93144798],
       [ 0.76473331,  1.36938298, -0.48593912,  1.06519365,  0.4495641 ,
         0.2566565 ],
       [-1.42303109, -0.93900609,  1.35462046, -0.7560761 ,  0.43782967,
        -1.92271185]], dtype=float32), array([[-0.33106405],
       [ 0.07557684],
       [-0.53173327],
       ..., 
       [-0.3988117 ],
       [ 0.17002617],
       [-0.43396717]], dtype=float32))


In [14]:
#How does the generated input data scattered? 
x = []
y = []
for i in range(10):
    xy = sess.run(batch_prov.batch())
    x.append(xy[0][0][0])
    y.append(xy[0][0][3])

plt.xlabel('x1')
plt.ylabel('x2')
plt.scatter(x, y)
plt.show()

TypeError: 'figure' is an unknown keyword argument

In [4]:
#How much the label depends on one axis?
#Now y is the label
plt.clf()
xys = []
for i in range(1000):
    xys.append(sess.run(batch_prov.batch()))
        
for axis in range(6):
    x = []
    y = []
    for i in range(1000):
        xy = xys[i]
        x.append(xy[0][0][axis])
        y.append(xy[1][0][0])

    plt.xlabel('data axis ' + str(axis))
    plt.ylabel('label')
    plt.scatter(x, y)
    plt.savefig('genereted_images/axis_' + str(axis) + '_vs_label.png')
    plt.clf()